---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-tile-automation 
- name: terraform-state

outputs:
- name: wipe-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

run:
  path: pcf-tile-automation/install-pcf/gcp/tasks/wipe-env/task.sh
