---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:
  SERVICE_NETWORK:
  SYSLOG_SELECTOR:
  SYSLOG_HOST:
  SYSLOG_PORT:
  DISABLE_TLS:  
  SMALL_PLAN_STATUS:
  MEDIUM_PLAN_STATUS:
  LARGE_PLAN_STATUS:
  BACKUPS_SELECTOR:
  S3_ACCESS_KEY:
  S3_SECRET_KEY:
  S3_ENDPOINT:
  S3_SIGNATURE:
  S3_BUCKET:
  S3_PATH:
  S3_SCHEDULE:
  ERRANDS_TO_DISABLE:
  ERRANDS_TO_WHENCHANGED:
  PREDELETE_ERRANDS_TO_DISABLE:

inputs:
  - name: pcf-tile-automation
  - name: tool-om

run:
  path: pcf-tile-automation/tasks/config-redis/task.sh
